### ISSUE TITLE
[NIP-0003] 냉장고 구매

### ISSUE THREAD

**Issue by tequila-kween** [s3unha/nonce#3]
```
NIP: 3
Title: 냉장고 구매
Author: 권혜리
Created: 2018-01-20
```

# 배경

지난번 집단 감기감염을 통한 논스 일시폐쇠 사건은 많은 분들이 건강의 중요성에 대해 다시한번 체감하는 기회가 되었다고 생각합니다. 
식음료는 건강과 직결된 매우 중요한 부분이기 때문에 **냉장고 구매를 통한 논스 주민 삶의 질 향상에 대한 제안**을 하고자 합니다. 

# 냉장고 부재에 따른 현황 및 문제점

1 현재 냉장고대신 발코니를 임시 방편으로 사용하고 있으나, 이 또한 하절기에는 사용 불가능 할것으로 판단됨.
2 배달음식이 남았을 경우 즉시 폐기하여야 함.
3 주류 및 음료를 시원하게 즐기지 못하며, 필요 시 일회성으로 구매하여야 함.
4 냉동 식품 보관 및 취식 불가
5 매 끼니 외식 혹은 배달식으로 인당 최소 6,000원 이상 지출 
6 식사 시 배달 또는 외출로 1시간 이상 소요됨.

# 냉장고 구매 시 기대효과

1 논스 주민 식습관 개선을 통한 건강 증진 
　　1.1 시간 소요가 심해 미루고 미루다가 식사를 하는 경우를 방지하여 폭식 및 야식 습관 개선
　　1.2 과일 및 야채 구비로 간식으로 불량식품 섭취하는 습관 개선
　　1.3 외부/배달식 취식 지양을 통한 염분 및 MSG 섭취 감소 
　　1.4 다이어트식 취식 가능 (대표적인 다이어트식으로 알려진 닭가슴살, 두부, 양배추 등은 냉장보관이 필수적임)

2 식비 절감
　　2.1 남은 음식의 보관 및 재취식 가능 
　　　　(논스 주민의 주식인 피자의 경우 냉장고 구매 시 남은 피자의 보관 및 취식이 매우 용이)
　　2.2 냉동식품, 반조리식품, 간식(우유, 요거트, 치즈 등) 구비를 통한 외식비 절감 
　　2.3 냉장보관 식품의 대량 구매를 통한 개당 가격 절감

3 시간 절약 
　　3.1 간단한 식사는 외식 및 배달 없이 논스에서 해결 가능 
　　3.2 찬 음료를 구매하러 외출하는 시간 절감

# 냉장고 구매 방법

1 비용 모금
　　1.1 구매 시점 거주민 대상 총 구매 가격의 1/n 씩 모금 (최대 100만원 초반 예상)
2 냉장고 모델 선정
　　1.1 비용 효율화를 위해 비용절감의 인센티브가 가장 큰 tequila-kween이 구매 옵션 선정(3안)
　　1.2 주민 투표를 거쳐 모델 선정 후 구매 진행 

# 후행 프로세스 
1 구매 결정시 냉장고 관리 방안 제정 필요 (청소, 보관기한 등)

Any comments and suggestions are welcome! :)

**Comment by IronPark** [comment]
해당 NIP는 이미 해결된 이슈로 냉장고 구입은 해결되었습니다. 따라서 본 NIP는 close 하는것을 권고합니다.

**Comment by tequila-kween** [comment]
네??????냉장고 언제사기로하셨어요

**Comment by tequila-kween** [comment]
냉장고가 생겨서 기쁩니다! >_<
